const PERFIX = "serverOperator/mutations/";
export const SETMIXSERVER = PERFIX + "SETMIXSERVER";
export const SETSERVER = PERFIX + "SETSERVER";
export const SETOPERATOR = PERFIX + "SETOPERATOR";
export const SAVECHOOSEMIXSERVER = PERFIX + "SAVECHOOSEMIXSERVER";
export const SAVECHOOSERSERVER = PERFIX + "SAVECHOOSERSERVER";
export const SAVECHOOSEOPERATOR = PERFIX + "SAVECHOOSEOPERATOR";
export const RESET = PERFIX + "RESET";